/**
 * @fileoverview gRPC-Web generated client stub for rocsys.os.local.v2alpha
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: proto/local.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.rocsys = {};
proto.rocsys.os = {};
proto.rocsys.os.local = {};
proto.rocsys.os.local.v2alpha = require('./local_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.AdministrationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.AdministrationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.GetTokenRequest,
 *   !proto.rocsys.os.local.v2alpha.GetTokenResponse>}
 */
const methodDescriptor_AdministrationService_GetToken = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.AdministrationService/GetToken',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.GetTokenRequest,
  proto.rocsys.os.local.v2alpha.GetTokenResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.GetTokenRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.GetTokenResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.GetTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.GetTokenResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.GetTokenResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.AdministrationServiceClient.prototype.getToken =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/GetToken',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_GetToken,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.GetTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.GetTokenResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.AdministrationServicePromiseClient.prototype.getToken =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/GetToken',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_GetToken);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.ApiVersionRequest,
 *   !proto.rocsys.os.local.v2alpha.ApiVersionResponse>}
 */
const methodDescriptor_AdministrationService_ApiVersion = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.AdministrationService/ApiVersion',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.ApiVersionRequest,
  proto.rocsys.os.local.v2alpha.ApiVersionResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.ApiVersionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.ApiVersionResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.ApiVersionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.ApiVersionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.ApiVersionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.AdministrationServiceClient.prototype.apiVersion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/ApiVersion',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_ApiVersion,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.ApiVersionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.ApiVersionResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.AdministrationServicePromiseClient.prototype.apiVersion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/ApiVersion',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_ApiVersion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.RocInfoRequest,
 *   !proto.rocsys.os.local.v2alpha.RocInfoResponse>}
 */
const methodDescriptor_AdministrationService_RocInfo = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.AdministrationService/RocInfo',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.RocInfoRequest,
  proto.rocsys.os.local.v2alpha.RocInfoResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.RocInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.RocInfoResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.RocInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.RocInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.RocInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.AdministrationServiceClient.prototype.rocInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/RocInfo',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_RocInfo,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.RocInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.RocInfoResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.AdministrationServicePromiseClient.prototype.rocInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/RocInfo',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_RocInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.EchoRequest,
 *   !proto.rocsys.os.local.v2alpha.EchoResponse>}
 */
const methodDescriptor_AdministrationService_Echo = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.AdministrationService/Echo',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.EchoRequest,
  proto.rocsys.os.local.v2alpha.EchoResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.EchoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.EchoResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.EchoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.EchoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.AdministrationServiceClient.prototype.echo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/Echo',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_Echo,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.EchoResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.AdministrationServicePromiseClient.prototype.echo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.AdministrationService/Echo',
      request,
      metadata || {},
      methodDescriptor_AdministrationService_Echo);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.DockBlockingRequest,
 *   !proto.rocsys.os.local.v2alpha.DockBlockingResponse>}
 */
const methodDescriptor_ACDCService_DockBlocking = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/DockBlocking',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.DockBlockingRequest,
  proto.rocsys.os.local.v2alpha.DockBlockingResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.DockBlockingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.DockBlockingResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.DockBlockingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.DockBlockingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.DockBlockingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.dockBlocking =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/DockBlocking',
      request,
      metadata || {},
      methodDescriptor_ACDCService_DockBlocking,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.DockBlockingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.DockBlockingResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.dockBlocking =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/DockBlocking',
      request,
      metadata || {},
      methodDescriptor_ACDCService_DockBlocking);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.DockAsyncRequest,
 *   !proto.rocsys.os.local.v2alpha.DockAsyncResponse>}
 */
const methodDescriptor_ACDCService_DockAsync = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/DockAsync',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.DockAsyncRequest,
  proto.rocsys.os.local.v2alpha.DockAsyncResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.DockAsyncRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.DockAsyncResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.DockAsyncRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.DockAsyncResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.DockAsyncResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.dockAsync =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/DockAsync',
      request,
      metadata || {},
      methodDescriptor_ACDCService_DockAsync,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.DockAsyncRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.DockAsyncResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.dockAsync =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/DockAsync',
      request,
      metadata || {},
      methodDescriptor_ACDCService_DockAsync);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.UndockBlockingRequest,
 *   !proto.rocsys.os.local.v2alpha.UndockBlockingResponse>}
 */
const methodDescriptor_ACDCService_UndockBlocking = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/UndockBlocking',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.UndockBlockingRequest,
  proto.rocsys.os.local.v2alpha.UndockBlockingResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.UndockBlockingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.UndockBlockingResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.UndockBlockingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.UndockBlockingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.UndockBlockingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.undockBlocking =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/UndockBlocking',
      request,
      metadata || {},
      methodDescriptor_ACDCService_UndockBlocking,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.UndockBlockingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.UndockBlockingResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.undockBlocking =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/UndockBlocking',
      request,
      metadata || {},
      methodDescriptor_ACDCService_UndockBlocking);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.UndockAsyncRequest,
 *   !proto.rocsys.os.local.v2alpha.UndockAsyncResponse>}
 */
const methodDescriptor_ACDCService_UndockAsync = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/UndockAsync',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.UndockAsyncRequest,
  proto.rocsys.os.local.v2alpha.UndockAsyncResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.UndockAsyncRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.UndockAsyncResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.UndockAsyncRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.UndockAsyncResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.UndockAsyncResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.undockAsync =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/UndockAsync',
      request,
      metadata || {},
      methodDescriptor_ACDCService_UndockAsync,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.UndockAsyncRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.UndockAsyncResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.undockAsync =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/UndockAsync',
      request,
      metadata || {},
      methodDescriptor_ACDCService_UndockAsync);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.HaltRequest,
 *   !proto.rocsys.os.local.v2alpha.HaltResponse>}
 */
const methodDescriptor_ACDCService_Halt = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/Halt',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.HaltRequest,
  proto.rocsys.os.local.v2alpha.HaltResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.HaltRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.HaltResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.HaltRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.HaltResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.HaltResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.halt =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/Halt',
      request,
      metadata || {},
      methodDescriptor_ACDCService_Halt,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.HaltRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.HaltResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.halt =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/Halt',
      request,
      metadata || {},
      methodDescriptor_ACDCService_Halt);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.AbortRequest,
 *   !proto.rocsys.os.local.v2alpha.AbortResponse>}
 */
const methodDescriptor_ACDCService_Abort = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/Abort',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.AbortRequest,
  proto.rocsys.os.local.v2alpha.AbortResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.AbortRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.AbortResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.AbortRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.AbortResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.AbortResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.abort =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/Abort',
      request,
      metadata || {},
      methodDescriptor_ACDCService_Abort,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.AbortRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.AbortResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.abort =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/Abort',
      request,
      metadata || {},
      methodDescriptor_ACDCService_Abort);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.StateRequest,
 *   !proto.rocsys.os.local.v2alpha.StateResponse>}
 */
const methodDescriptor_ACDCService_StatePoll = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/StatePoll',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.StateRequest,
  proto.rocsys.os.local.v2alpha.StateResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.StateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.StateResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.StateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.StateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.StateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.statePoll =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/StatePoll',
      request,
      metadata || {},
      methodDescriptor_ACDCService_StatePoll,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.StateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.StateResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.statePoll =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/StatePoll',
      request,
      metadata || {},
      methodDescriptor_ACDCService_StatePoll);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.StateRequest,
 *   !proto.rocsys.os.local.v2alpha.StateResponse>}
 */
const methodDescriptor_ACDCService_StateStream = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ACDCService/StateStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.rocsys.os.local.v2alpha.StateRequest,
  proto.rocsys.os.local.v2alpha.StateResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.StateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.StateResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.StateRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.StateResponse>}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServiceClient.prototype.stateStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/StateStream',
      request,
      metadata || {},
      methodDescriptor_ACDCService_StateStream);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.StateRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.StateResponse>}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ACDCServicePromiseClient.prototype.stateStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rocsys.os.local.v2alpha.ACDCService/StateStream',
      request,
      metadata || {},
      methodDescriptor_ACDCService_StateStream);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.ManagementServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.ManagementServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.AutoRecoverBlockingRequest,
 *   !proto.rocsys.os.local.v2alpha.AutoRecoverBlockingResponse>}
 */
const methodDescriptor_ManagementService_AutoRecoverBlocking = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ManagementService/AutoRecoverBlocking',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.AutoRecoverBlockingRequest,
  proto.rocsys.os.local.v2alpha.AutoRecoverBlockingResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.AutoRecoverBlockingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.AutoRecoverBlockingResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.AutoRecoverBlockingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.AutoRecoverBlockingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.AutoRecoverBlockingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ManagementServiceClient.prototype.autoRecoverBlocking =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/AutoRecoverBlocking',
      request,
      metadata || {},
      methodDescriptor_ManagementService_AutoRecoverBlocking,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.AutoRecoverBlockingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.AutoRecoverBlockingResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ManagementServicePromiseClient.prototype.autoRecoverBlocking =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/AutoRecoverBlocking',
      request,
      metadata || {},
      methodDescriptor_ManagementService_AutoRecoverBlocking);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.AutoRecoverAsyncRequest,
 *   !proto.rocsys.os.local.v2alpha.AutoRecoverAsyncResponse>}
 */
const methodDescriptor_ManagementService_AutoRecoverAsync = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ManagementService/AutoRecoverAsync',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.AutoRecoverAsyncRequest,
  proto.rocsys.os.local.v2alpha.AutoRecoverAsyncResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.AutoRecoverAsyncRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.AutoRecoverAsyncResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.AutoRecoverAsyncRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.AutoRecoverAsyncResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.AutoRecoverAsyncResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ManagementServiceClient.prototype.autoRecoverAsync =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/AutoRecoverAsync',
      request,
      metadata || {},
      methodDescriptor_ManagementService_AutoRecoverAsync,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.AutoRecoverAsyncRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.AutoRecoverAsyncResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ManagementServicePromiseClient.prototype.autoRecoverAsync =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/AutoRecoverAsync',
      request,
      metadata || {},
      methodDescriptor_ManagementService_AutoRecoverAsync);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.ConfirmRecoveryRequest,
 *   !proto.rocsys.os.local.v2alpha.ConfirmRecoveryResponse>}
 */
const methodDescriptor_ManagementService_ConfirmRecovery = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ManagementService/ConfirmRecovery',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.ConfirmRecoveryRequest,
  proto.rocsys.os.local.v2alpha.ConfirmRecoveryResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.ConfirmRecoveryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.ConfirmRecoveryResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.ConfirmRecoveryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.ConfirmRecoveryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.ConfirmRecoveryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ManagementServiceClient.prototype.confirmRecovery =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/ConfirmRecovery',
      request,
      metadata || {},
      methodDescriptor_ManagementService_ConfirmRecovery,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.ConfirmRecoveryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.ConfirmRecoveryResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ManagementServicePromiseClient.prototype.confirmRecovery =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/ConfirmRecovery',
      request,
      metadata || {},
      methodDescriptor_ManagementService_ConfirmRecovery);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.ReleaseToOperationalRequest,
 *   !proto.rocsys.os.local.v2alpha.ReleaseToOperationalResponse>}
 */
const methodDescriptor_ManagementService_ReleaseToOperational = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ManagementService/ReleaseToOperational',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.ReleaseToOperationalRequest,
  proto.rocsys.os.local.v2alpha.ReleaseToOperationalResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.ReleaseToOperationalRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.ReleaseToOperationalResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.ReleaseToOperationalRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.ReleaseToOperationalResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.ReleaseToOperationalResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ManagementServiceClient.prototype.releaseToOperational =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/ReleaseToOperational',
      request,
      metadata || {},
      methodDescriptor_ManagementService_ReleaseToOperational,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.ReleaseToOperationalRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.ReleaseToOperationalResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ManagementServicePromiseClient.prototype.releaseToOperational =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ManagementService/ReleaseToOperational',
      request,
      metadata || {},
      methodDescriptor_ManagementService_ReleaseToOperational);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.ROCServiceServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rocsys.os.local.v2alpha.ROCServiceServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.StatePlusRequest,
 *   !proto.rocsys.os.local.v2alpha.StatePlusResponse>}
 */
const methodDescriptor_ROCServiceService_StatePollPlus = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ROCServiceService/StatePollPlus',
  grpc.web.MethodType.UNARY,
  proto.rocsys.os.local.v2alpha.StatePlusRequest,
  proto.rocsys.os.local.v2alpha.StatePlusResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.StatePlusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.StatePlusResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.StatePlusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rocsys.os.local.v2alpha.StatePlusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.StatePlusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ROCServiceServiceClient.prototype.statePollPlus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ROCServiceService/StatePollPlus',
      request,
      metadata || {},
      methodDescriptor_ROCServiceService_StatePollPlus,
      callback);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.StatePlusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rocsys.os.local.v2alpha.StatePlusResponse>}
 *     Promise that resolves to the response
 */
proto.rocsys.os.local.v2alpha.ROCServiceServicePromiseClient.prototype.statePollPlus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rocsys.os.local.v2alpha.ROCServiceService/StatePollPlus',
      request,
      metadata || {},
      methodDescriptor_ROCServiceService_StatePollPlus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rocsys.os.local.v2alpha.StatePlusRequest,
 *   !proto.rocsys.os.local.v2alpha.StatePlusResponse>}
 */
const methodDescriptor_ROCServiceService_StateStreamPlus = new grpc.web.MethodDescriptor(
  '/rocsys.os.local.v2alpha.ROCServiceService/StateStreamPlus',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.rocsys.os.local.v2alpha.StatePlusRequest,
  proto.rocsys.os.local.v2alpha.StatePlusResponse,
  /**
   * @param {!proto.rocsys.os.local.v2alpha.StatePlusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rocsys.os.local.v2alpha.StatePlusResponse.deserializeBinary
);


/**
 * @param {!proto.rocsys.os.local.v2alpha.StatePlusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.StatePlusResponse>}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ROCServiceServiceClient.prototype.stateStreamPlus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rocsys.os.local.v2alpha.ROCServiceService/StateStreamPlus',
      request,
      metadata || {},
      methodDescriptor_ROCServiceService_StateStreamPlus);
};


/**
 * @param {!proto.rocsys.os.local.v2alpha.StatePlusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rocsys.os.local.v2alpha.StatePlusResponse>}
 *     The XHR Node Readable Stream
 */
proto.rocsys.os.local.v2alpha.ROCServiceServicePromiseClient.prototype.stateStreamPlus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rocsys.os.local.v2alpha.ROCServiceService/StateStreamPlus',
      request,
      metadata || {},
      methodDescriptor_ROCServiceService_StateStreamPlus);
};


module.exports = proto.rocsys.os.local.v2alpha;

